export const icons = {
    penciledit: require('../../assets/icons/pencil-edit.png'),
    greentick: require('../../assets/icons/green-tick.png'),
    cross2: require('../../assets/icons/cross2.png'),
    warning: require('../../assets/icons/warning.png'),
    shop: require('../../assets/icons/shop.png'),
    shopfill: require('../../assets/icons/shop-fill.png'),
    bag: require('../../assets/icons/bag.png'),
    bagfill: require('../../assets/icons/bag-fill.png'),
    heart: require('../../assets/icons/heart.png'),
    heartfill: require('../../assets/icons/heart-fill.png'),
    userfill: require('../../assets/icons/user-fill.png'),
    user: require('../../assets/icons/user.png'),
    bell: require('../../assets/icons/bell.png'),
    bellfill: require('../../assets/icons/bell-fill.png'),
    back: require('../../assets/icons/back.png'),
    share: require('../../assets/icons/mega-share.png'),
    search: require('../../assets/icons/search.png'),
}